{% set name = "tinycss2" %}
{% set version = "1.5.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d339d2b616ba90ccce58da8495a78f46e55d4d25f9fd71dfd526f07e7d53f957

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - flit-core >=3.2,<4
  run:
    - python
    - webencodings >=0.4

test:
  source_files:
    - tests
  imports:
    - tinycss2
  requires:
    - pip
    - pytest
    - ruff
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v

about:
  home: https://www.courtbouillon.org/tinycss2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Low-level CSS parser for Python
  description: |
    tinycss2 is a low-level CSS parser and generator written in Python: it can parse strings,
    return objects representing tokens and blocks, and generate CSS strings corresponding to these objects.
  doc_url: https://doc.courtbouillon.org/tinycss2
  dev_url: https://github.com/Kozea/tinycss2

extra:
  recipe-maintainers:
    - johanneskoester
    - mrandrewandrade
    - thewchan
