travis:
  secure:
    BINSTAR_TOKEN: GS199bCje2vB6lNFfs0GMPuS5W0LIWFQTFnp9ZibID4I2hfu3gDf78NyTs6ZOOnc81eUVAKeR+Jn46nyNsDyXlMQWBJ8ECtSEPwdayUeAE++NV+cOE5wvdRLyiHF2lXiH0is3+W5LPGHIwfM2IesM0D1wBwqkMFEU0HraKwvDe0osDOGOOX/WIftNiLPGW+xYB5RcwbpdTVw7IPkyO5i0rDxusBQwp+pwtu5a6L25MsJEzo+1Nwkb6/P/qkFBx3XOhjj5M/+P0QrgvR6qUyQ5ceKePQXE4HqXb1Ti5AennoKsgre5KR5gRjjoQhLWrj8LocqlLsE4zZNF1TQ80TkXxzzmrPLlCu8Ty6fCUD+mq6aiBkSuGfBNUZ57KPrdIXTHj6XufjdSOEqfjKlOo1OgkBKGbXfWjOyqmhcu+lEK61/umckbl5XjMr3gwsRwpMMlxXThJW4sf3SwyAt+l5U8ok3QTUZ7amT5gh0Ko9STaG7g0OHhHXIYGIolALiaCETJEfnstZgnRqh0ckXW7SdGnopqnmAn5lEG/fU/F/vp3Y1mnYmplJUa6lCnmc00hM3FPI6/+X4NLZxUszNvvdvdXZJ3Zo2rauMmxfDBbA72xsDDzqa6kgAJZ5Q4pct/mfnZJu7QNuFDEMT5IXw4pInWGOv0CZK288AclJ+et9DAd8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
