travis:
  secure:
    BINSTAR_TOKEN: wtf//Iuq6ASCE5GYPGXLAyzInpFXGGWeGDoKAye75o+yhdGqJ+/uIfePXVC6r+1Ah0Sye7WELe07jVHNdhvg/QFV3hqM3BynTXRMV4TxJKjN4PU2nZc4Em6rxH93+FS42VQtZz0A+9ceM7F2An+7sCzvmljhQbkv3DTlc6Y4cpVuCX4gvaimGCsdmb79ielAfz5aib3yU/vzITNGLxhFFnKjq5rA31CpyO4FmrpTghYqXKTq3CpoKYHM1CLkB3UAGFwhflj6J5c6KHX9tHO5oucZC/U2RbiMspIFksq4ibLBaKZF7Wqvnbh2801xIvadz8SpYcDkrdv95wg2IeYBFW+rsaRAAcUj2id8rbodB0/1oiVTYrCahubAKFZzc1mdbL2oJVC0gHLv5eEEHZ1O30n31mQc5m6VJu5Lok3Uhlay+S4obAUK/0NVL3xhkofIkPEpM2QSKGKUBYT/xMpAnWFZ4YoPi8ImvmoPdAWPGno2BcpnUNSbozGXr4XtSBVIlMklnKXtYeSTDRQg0bXNGRITu7C8aHm66KrVIP9mJLMT5AaM/jSX509VSNXyCopn2xcpiQFRbHlbCfV8Cq+FWJjgPGvAjsxkgHZfvaiWS2Gb6QVBcO6CMWt435oF82+6gj0Rvsj7oYs+rQePOpxeSfi0y2M7LtXUDt6ulHki8dw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
